name: Deploy to Azure

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_BACKEND: notebook-backend
  AZURE_WEBAPP_FRONTEND: notebook-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build and push backend
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} \
            --image notebook-backend:${{ github.sha }} \
            --file backend/Dockerfile backend/
      
      - name: Build and push frontend
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} \
            --image notebook-frontend:${{ github.sha }} \
            --file frontend/Dockerfile frontend/
      
      - name: Deploy to Container Apps
        run: |
          az containerapp update \
            --name ${{ env.AZURE_WEBAPP_BACKEND }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/notebook-backend:${{ github.sha }}
          
          az containerapp update \
            --name ${{ env.AZURE_WEBAPP_FRONTEND }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/notebook-frontend:${{ github.sha }}
